import random
template_num = input("Welcome to the game Mad Libs! Please choose a template by typing 1, 2, 3 or random (for a randomly generated template): ")

if template_num == "random":
    template_num = str(random.randint(1, 3))
   
if template_num == "1":
    template1 = "It was about " + input("Type a number: ") + " " + input("Type a measure of time (hours, minutes, etc.): ") + " ago when I arrived at the hospital in a " + input("Type a mode of transportation: ") + ". The hospital is a/an " + input("Type an adjective: ") + " place, there are a lot of " + input("Type another adjective: ") + " " + input("Type a plural noun: ") + " here. There are nurses here who have " + input("Type a color: ") + " " + input("Type a part of the body(plural): ") + ". If someone wants to come into my room I told them that they have to " + input("Type a verb: ") + " first. I've decorated my room with " + input("Type a number: ") + " " + input("Type a plural noun if previous number wasn't 1, otherwise input a noun: ") + ". Today I talked to a doctor and they were wearing a " + input("Type a noun: ") + " on their " + input("Type a part of the body: ") + ". I heard that all doctors " + input("Type a verb: ") + " " + input("Type a plural noun: ") + " every day for breakfast. The most " + input("Type an adjective: ") + " thing about being in the hospital is the " + input("Type a silly word: ") + " " + input("Type a noun: ") + "!"
    print(template1)
elif template_num == "2":
    template2 = "This weekend I am going camping with " + input("Type a full name: ") + ". I packed my lantern, sleeping bag, and " + input("Type a noun: ") + ". I am so " + input("Type an adjective (feeling): ") + " to " + input("Type a verb: ") + " in a tent. I am " + input("Type an adjective (feeling): ") + " we might see a/an " + input("Type an animal: ") + ", I hear they're kind of dangerous. While we're camping, we are going to hike, fish, and " + input("Type a verb: ") + ". I have heard that the " + input("Type a color: ") + " lake is great for " + input("Type a verb ending in ing: ") + ". Then we will " + input("Type an adverb (ending in ly): ") + " hike through the forest for " + input("Type a number: ") + " " + input("Type a measure of time(hours, minutes, etc.): ") + ". If I see a " + input("Type a color: ") + " " + input("Type an animal: ") + " while hiking, I am going to bring it home as a pet! At night we will tell " + input("Type a number: ") + " " + input("Type a silly word: ") + " stories and roast " + input("Type a plural noun: ") + " around the campfire!!"
    print(template2)
elif template_num == "3":
    template3 = "Dear " + input("Type a full name: ") + ", I am writing to you from a/an " + input("Type an adjective: ") + " castle in an enchanted forest. I found myself here one day after going for a ride on a/an " + input("Type a color: ") + " " + input("Type an animal: ") + " in " + input("Type a place: ") + ". There are " + input("Type an adjective: ") + " " + input("Type a magical creature (plural): ") + " and " + input("Type an adjective: ") + " " + input("Type a magical creature (plural): ") + " here! In the " + input("Type a room in a house: ") + " there is a pool full of " + input("Type a noun: ") + ". I fall asleep each night on a/an " + input("Type another noun: ") + " of " + input("Type a plural noun: ") + " and dream of " + input("Type an adjective: ") + " " + input("Type a plural noun: ") + ". It feels as though I have lived here for " + input("Type a number: ") + " " + input("Type a measure of time(hours, minutes, etc.): ") + ". I hope one day you can visit, although the only way to get here now is by " + input("Type a verb ending with ing: ") + " on a/an " + input("Type an adjective: ") + " " + input("Type a noun: ") + "!!"
    print(template3)
else:
    print("ERROR")
    print("Please run the file again and input correctly!")